### PR TITLE
add go project stubbing.

### PR DESCRIPTION
**Pull request by mbachtel**
PR adds default project structure for go projects

### CODE REVIEW

**Comment by davidewatson** [comment]
This repo is intended to be a generic template for arbitrary GitHib repos. For golang specific GitHub repos, please fork https://github.com/samsung-cnct/golang-tools.

@mikeln: Do you mind if we renamed golang-tools to solas-golang to make the relationship more clear?

**Comment by mikeln** [comment]
@davidewatson strongly mind a rename.

**Comment by mikeln** [comment]
Also, the intent is not to fork https://github.com/samsung-cnct/golang-tools for new golang project repos.  But use the appropriate example setup from one of the subdirs as the initial population of the new project.
e.g.  COPY  https://github.com/samsung-cnct/golang-tools/example-project into your new project repo.

**Comment by davidewatson** [comment]
Closing as the wrong repo. I think it would be useful if we had something like https://github.com/thockin/go-build-template as a starting point for cnct golang apps, but perhaps the tutorial approach of golang-tools is better than forking.

**Pull request closed without merging**
